### ISSUE TITLE
페이지별 컴포넌트, 경로 정리

### ISSUE THREAD

**Issue by localgaji** [Step3-kakao-tech-campus/Team1_FE#10]
https://docs.google.com/spreadsheets/d/1VSTwSfau1B9YM9MM9IERQ_ABu--7lYJsP7oMeCNKxx0/edit?usp=sharing

와이어프레임에 나와있는 페이지별로 컴포넌트 구조 모두 다 정리했습니다
컴포넌트 재활용에 대해서도 표시 해두었는데 노션에 정리해두신거랑 종합해보면 마무리될거같아요
그리고 커스텀 컴포넌트 이름을 개발하면서 즉석으로 지으면 중구난방되는것 같아서 미리 생각해서 등록해두면 좋을것같아요

수정사항 있으시면 말씀해주세요!

**Comment by harin9** [comment]
오 제가 노션에 정리해둔 게 필요 없을 정도인데요!!
저는 재활용될 큼직한 컴포넌트 위주로 정리했고, 이름도 컴포넌트 이름으로 정리해 두었습니다.
노션 쪽도 얼추 완료되었는데 확인 부탁드릴게요!
현지님께서 정리해두신 문서도 읽어보겠습니다:)

**Comment by harin9** [comment]
> 오 제가 노션에 정리해둔 게 필요 없을 정도인데요!! 저는 재활용될 큼직한 컴포넌트 위주로 정리했고, 이름도 컴포넌트 이름으로 정리해 두었습니다. 노션 쪽도 얼추 완료되었는데 확인 부탁드릴게요! 현지님께서 정리해두신 문서도 읽어보겠습니다:)

그리고 버튼 컴포넌트와 인풋박스는 이미 만들어서 커밋까지 해둔 상태입니다!! 이 정도는 이름을 굳이 바꿀 필요는 없을 것 같아요 ㅎㅎ...
