### ISSUE TITLE
UI 수정사항 반영

### ISSUE THREAD

**Issue by localgaji** [Step3-kakao-tech-campus/Team1_FE#14]
https://www.notion.so/UI-Figma-6a3bb243b43948c7bc4e7e89f0c9ae25

어제 회의에서 기획 UI 쪽에 수정한 부분이 있습니다 

피그마 `UI - 회원 관리 : 반응형 구조 수정` 섹션에 있는 페이지들은 모두 반응형으로 고쳤습니다.
이 섹션에 있는 페이지들은 디자인 추가 수정사항 아마 없을것 같아서 피그마대로 사용하시면 됩니다
컴포넌트 css 적용할때 사용해주세요!!

그리고 상단바 하단바 아이콘들 피그마에 있는거 그대로 써야 할것 같습니다. 
피그마 `UI 리소스2 - 실사용` 섹션에 상단바 하단바 컴포넌트가 있는데
하단바 아이콘 레이어를 살펴보시면 on 버전과 off 버전이 둘다 포함되어 있습니다.
이 컴포넌트들도 마찬가지로 반응형으로 구성되어 있으니 css 활용하시면 됩니다.

**Comment by harin9** [comment]
확인이 늦었습니다! 피그마 반영하는 부분들은 내일 오후에 가능할 것 같습니다..!

**Comment by localgaji** [comment]
컨테이너 모달 없으면 ui 적용 시작이 안돼서 일단 제가 거의 만들었어요

**Comment by harin9** [comment]
제가 push 안한지 몰랐네요ㅠㅠ.. 방금 했습니다 전에 보냈던 pr에 쌓여 있어요! 그럼 지금 모달까지 만드신 건가요? 어느 부분 작업하고 계신 건가요??

**Comment by localgaji** [comment]
https://github.com/Step3-kakao-tech-campus/Team1_FE/pull/21 지금 여기까지 했습니다

**Comment by localgaji** [comment]
일단 #21 문제 없으면 weekly로 merge 할게요!

**Comment by harin9** [comment]
넵! 피그마 반영해서 스타일링 해보려고 했는데 어떻게 하는지 잘 모르겠네요ㅠㅠ... 일단 조금 더 알아보겠습니다. 오늘까지 제출이니 제가 올린 pr도 머지 해도 괜찮을까요??

**Comment by localgaji** [comment]
제가 merge 하고 충돌이나 중복 파일 해결하겠습니다

**Comment by harin9** [comment]
앗 넵 감사합니다!
