### ISSUE TITLE
프론트엔드 기초 설정

### ISSUE THREAD

**Issue by localgaji** [Step3-kakao-tech-campus/Team1_FE#2]
### 언어

- 타입스크립트
- React.FC 사용 X, JSX.Element 사용
- npm

### 라이브러리

- [x]  react-router-dom
- [x]  redux toolkit & redux persist
- [x]  react error boundary
- [x]  react query
- [x]  axios
- [x]  react-icons
- [x]  Styled-components
- [x]  tailwind

### 코드 스타일

- Prettier
- ESLint
- 함수형 컴포넌트 : 화살표 함수 vs 그냥 함수
- [코드 스니펫](https://www.notion.so/2d25a98f5d4a4973a937a7bda73bfe11?pvs=21)

### 디렉토리

- 절대 경로 사용
- scr 내부 디렉터리의 기본 구조

```
📂 public
 ┣ 📂 images           // 로고 등
 ┗ 📄 index.html
📂 src
 ┣ 📂 apis             // axios 관련
 ┣ 📂 assets
 ┣ 📂 auth             // 접근 권한 routes
 ┣ 📂 components       
    ┣ 📂 atoms
    ┣ 📂 molecules
    ┣ 📂 organisms
    ┗ 📂 templates
 ┣ 📂 states           // 리덕스 관련
    ┣ 📂 slices        // 리덕스 슬라이스
    ┣ 📄 index.js      // rootReducer
    ┗ 📄 store.js      // store
 ┣ 📂 hooks            // 커스텀 훅
 ┣ 📂 pages            // 페이지
 ┣ 📂 utils            // validator, 숫자 형식, 정규표현식 등 
 ┣ 📄 App.js
 ┗ 📄 index.js
```

- 컴포넌트 구조 : 아토믹 컴포넌트 구조 쓸건지, 다른 구조에는 어떤게 있는지?  → 아토믹 컴포넌트 구조
- 리액트 쿼리는 template 이하/organism 레벨에서 사용

### Atomic Component Design 구조 기준

1. atoms : 구조가 매우 간단하고 재활용이 가능한 컴포넌트 ex) 버튼, input
2. molecules : 두개 이상의 element로 이루어져 있고 단독으로는 사용할 수 없는 컴포넌트 ex) 체크+라벨 한세트, input+라벨 한세트, 목록 중에서 한개
3. organisms : 단독으로 사용할 수 있는 컴포넌트 ex) 로그인 폼, 스케줄 표, navigation bar,  모달, 토스트
4. templates : 페이지의 뼈대를 조합하는 컴포넌트
5. pages : 페이지

모바일 위주라 구조가 간단하므로 templates 은 필요없으면 생략하기

**Comment by localgaji** [comment]
기초설정 weekly에 merge 되었으니 다운 받으셔서 정상적으로 실행 되는지 리뷰 부탁드립니다.

**Comment by harin9** [comment]
음, 기초 설정은 되었습니다만, tailwind pr 전에 이미 클론 + 컴포넌트 간단한 거 두 개 정도 만든 상태입니다. 그대로 진행하면 conflict가 생길까요?? 어떻게 생각하시나욥...

**Comment by localgaji** [comment]
tailwind 설치 PR 들어가시면 수정한 파일 목록 보실수 있습니다 저 파일들 수정하신거 아니면 conflict는 안생겨요

**Comment by harin9** [comment]
> tailwind 설치 PR 들어가시면 수정한 파일 목록 보실수 있습니다 저 파일들 수정하신거 아니면 conflict는 안생겨요

제가 임의로 tailwind 설치했거든요...ㅎㅅㅎ... 일단 해보겠습니다

**Comment by localgaji** [comment]
충돌 일어나도 config 파일들 뿐이라서 merge할때 해결하면 되니까 괜찮아요 아직 커밋 안하셨으면 저 파일들은 빼고 커밋하면 됩니다

**Comment by harin9** [comment]
옙 감사합니다!!
