### ISSUE TITLE
객체 타입 지정 방식 통일

### ISSUE THREAD

**Issue by localgaji** [Step3-kakao-tech-campus/Team1_FE#25]
props 타입 지정할때 interface 로 통일하기로 했는데 혹시 type으로 하신 이유가 있으신가요?
중요한건 아니지만 한쪽으로 통일해야 할것 같습니다.

**Comment by harin9** [comment]
헉 그르네요 지금까지 스니펫을 tsrafce로 쓰고 있었어요... 수정하겠습니다!!
