### ISSUE TITLE
디자인 세부 사항 반영

### ISSUE THREAD

**Issue by localgaji** [Step3-kakao-tech-campus/Team1_FE#27]
작성된 페이지의 디자인 세부사항 적용 부탁드립니다
피그마와 똑같을 필요는 없을것 같아요!

그리고 스타일드 컴포넌트 설정파일에 커스텀 값들을 지정해놓았습니다.
https://ella951230.tistory.com/m/entry/%EB%A6%AC%EC%95%A1%ED%8A%B8-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-styled-components-theme-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0

https://github.com/Step3-kakao-tech-campus/Team1_FE/blob/weekly/src/styles/myTheme.ts

참고하셔서 프로젝트에서 자주 쓰이는 컬러, 폰트, 글자 크기 등은 변경사항이 생길 시 일괄 변경할 수 있도록
이 커스텀 값 이용하여 지정 부탁드립니다.

폰트는 base , medium 을 기본값으로 하면 될 것 같습니다

**Comment by localgaji** [comment]
공용 컴포넌트들은 테일윈드 말고 스타일드로 지정해주시면 좋을것 같습니다.

**Comment by harin9** [comment]
넵! 스타일드 컴포넌트 theme 지정해두신 거면 머지된 weekly를 pull 땡겨온 뒤에 사용하면 될까요?

**Comment by localgaji** [comment]
네 지금 브랜치는 없애고 디자인 브랜치 생성 후 weekly pull 하셔서 사용해주세요
