### ISSUE TITLE
커밋 컨벤션 + 커밋 단위 정하기

### ISSUE THREAD

**Issue by localgaji** [Step3-kakao-tech-campus/Team1_FE#4]
### 커밋 컨벤션
```
feat : 새로운 기능 추가
fix : 버그 수정
docs : 문서 수정
design : 디자인 수정
style : 코드 포맷팅, 세미콜론 누락, 코드 변경이 없는 경우
refactor : 코드 리팩토링
type : 타입 수정
test : 테스트 코드, 리펙토링 테스트 코드 추가
chore : 빌드 업무 수정, 패키지 매니저 수정
init : 프로젝트 초기 생성
move : 파일 이동
rename : 파일 이름 변경
remove : 파일 삭제
comment : 주석 추가 / 변경
```

### 커밋 메세지
type: 변경사항 설명
  
  

### 커밋 단위
뭉텅이 커밋을 지양하고 최대한 잘개 쪼개서 커밋 하는것을 제안합니다. 
  
장점 - 문제가 발생한 시점을 쉽게 파악할 수 있음, 커밋 메세지에 수정사항을 명료하게 작성 가능
단점 - 귀찮음 (저는 처음에는 귀찮았는데 하다보니 익숙해진것 같습니다. vsc git 메뉴 사용)
  
최소한 파일 한개 수정할 때마다 커밋을 하는게 효율적이라고 생각합니다. 
또 파일 한개를 수정하더라도 예를 들어서 한 파일에서 기능이랑 ui 를 수정했으면 이 두개를 따로 커밋 보내는게 좋을것 같습니다. 

커밋 단위에 대해 의견을 댓글에 말씀해주세요

https://letsgojieun.tistory.com/m/146
https://tech.10000lab.xyz/git/git-commit-discipline.html
https://jaeheon.kr/257
https://velog.io/@suker80/Git-Commit-%EB%8B%A8%EC%9C%84%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%AA%BC%EA%B0%9C%EB%8A%94%EA%B2%8C-%EC%A2%8B%EC%9D%84%EA%B9%8C
https://careerly.co.kr/comments/79784
https://seongkyun-yu.github.io/2020/12/28/0060-why-small-commit/

**Comment by harin9** [comment]
좋습니다. 최대한 잘게 쪼개보겠습니다. vsc git 메뉴라는 건 source control 메뉴를 말씀하시는 건가요?

**Comment by localgaji** [comment]
네맞습니다 저는 저걸로 하긴하는데 편하신거 사용하면 될거같아요
