### ISSUE TITLE
프론트엔드 Route 경로 정하기

### ISSUE THREAD

**Issue by localgaji** [Step3-kakao-tech-campus/Team1_FE#7]
이거 피그마에 최종적으로 정리해뒀는데 검토 부탁드립니다.

**Comment by harin9** [comment]
좋습니다! 그런데 메인은 가장 처음에 영상 재생되는 페이지를 말하는 건가요, 아니면 스케줄 조회 페이지인가요?

전자라면, 

**메인(영상)**
```
/
```
**스케줄 조회**
```
/main
```

후자라면,

**메인(스케줄 조회)**
```
/
```
**영상 있는 페이지**
```
/main
```

이 되면 혼란스러울까요? 어떻게 생각하고 계시는지 궁금합니다.

**Comment by localgaji** [comment]
로그인 여부에 따라서 같은 `/` 경로에서 다른 페이지를 보여주게 되는거 아닐까요 
온보딩 화면이 로그인전 메인화면이고 스케줄 화면이 로그인후 메인 화면인데 저는 두개를 구분할 필요성을 잘 모르겠어요. 혹시 이유가 있을까요?

**Comment by localgaji** [comment]
같은 `/` 경로로 접속했을때 로그인 여부에 따라 다른 페이지가 노출되는것 같아요
로그인 전에는 온보딩 화면, 로그인 후에는 스케줄 화면이 노출되는데 둘다 기본 도메인에서 이루어져야 하니까요
두 페이지 경로를 혹시 구분하시는 이유가 따로 있나요?

**Comment by harin9** [comment]
> 같은 `/` 경로로 접속했을때 로그인 여부에 따라 다른 페이지가 노출되게 해야하는것 같아요 로그인 전에는 온보딩 화면, 로그인 후에는 스케줄 화면이 노출되는데 둘다 기본 url 에서 이루어져야 하니까요 두 페이지 경로를 혹시 구분하시는 이유가 따로 있나요?

아하 둘 다 같은 경로에서 노출만 다르게 하는군요,,, 넵 알겠습니다!!

**Comment by localgaji** [comment]
피그마와 엑셀에 마저 정리해두었습니다
