### ISSUE TITLE
사이드바

### ISSUE THREAD

**Issue by localgaji** [Step3-kakao-tech-campus/Team1_FE#71]
## 할 일 요약

사이드바를 구현
  
  
## 세부 사항
- 사이드바 노출
  - [x] 헤더 메뉴버튼 클릭시 나타나도록 하기
  - [x] 빈 공간 클릭시 사라지도록 하기
- 매니저 사이드바
  - [x] 기능
    - [x] 직원 초대하기 모달 띄우기 : useModal 훅, GetInviteKey 컴포넌트 활용
    - [x] 내 정보 불러오기
    - [x] 그룹원 리스트 불러오기
    - [x] 로그아웃 버튼
  - [x]  UI
  - [ ]  코드 다듬기
- 알바생 사이드바
  - [x] 기능
    - [x] 내 정보 불러오기
    - [x] 그룹원 리스트 불러오기
    - [x] 로그아웃 버튼
  - [x]  UI
  - [ ]  코드 다듬기

**Comment by harin9** [comment]
안녕하세요 현지님. 
본문의 두 번째 매니저 사이드바는 알바생 사이드바로 이해해도 괜찮을까요? 

감사합니다!

**Comment by localgaji** [comment]
아 넵 수정했습니다
