### ISSUE TITLE
초대 링크 복사 시 토스트로 알림주기

### ISSUE THREAD

**Issue by harin9** [Step3-kakao-tech-campus/Team1_FE#73]
## AS-IS
  현재 피그마 기준으로는 별다른 구현이 되어있지 않는 것 같습니다.
  
## TO-BE
  초대 링크 복사하기 버튼을 클릭 시 복사 성공 여부를 토스트로 알려주는 건 어떨까요?
괜찮다면 사이드바 구현 시 함께 작업하겠습니다!

**-> 링크 복사 성공 시 버튼 ui가 변경되도록 작업.**

  
## 변경해야할 목록
  - [ ] 목록1
  - [ ] 목록2
  - [ ] 목록3
  - [ ] 목록4

**Comment by localgaji** [comment]
초대링크 컴포넌트는 `GetInviteKey.tsx` 에 이미 구현되어있고 사이드바에서 모달 on 되도록 상태관리만 해주시면 됩니다
복사여부는 버튼 변경하는걸로 알려줘도 될것 같아요
추후 수정하겠습니다

**Comment by harin9** [comment]
앗 그러네요,, 일단 컴포넌트 없이 구현하고 pr에 반영을... 했습니다,,😂

**Comment by localgaji** [comment]
사이드바 PR에서는 사이드바 부분만 하고 초대하기 모달 내부는 분리해서 작업 하는게 맞는것 같네용

그리고 BE 멘토링시간에 들은거긴한데 브랜치에 이슈 번호 붙이는거 추천한다고 하셔서 
feat-#00-브랜치명 
이런식으로 브랜치 네이밍 하고 이슈마다 PR 하면 좋을것 같아요!

**Comment by harin9** [comment]
넵 !! 알겠습니다! 그럼 그 부분은 사이드바 작업 마친 후에 반영해보도록 하겠습니다.

오 브랜치명 뭔가 관리하기가 힘들 것 같았는데 좋은 방법 같습니다...! 다음 작업부터는 브랜치명 네이밍 통일해 볼게요! pr과 이슈도 남기도록 하겠습니다...☺️
